# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseDiagCross <- function(A, M, B, n) {
    .Call(`_sparseutils_sparseDiagCross`, A, M, B, n)
}

sparseDiagDot <- function(A, D, B, n) {
    .Call(`_sparseutils_sparseDiagDot`, A, D, B, n)
}

sparseSandwichTrace <- function(L, M, Q, R, n, n0) {
    .Call(`_sparseutils_sparseSandwichTrace`, L, M, Q, R, n, n0)
}

sparseSandwichDiag <- function(L, M, Q, R, n, n0) {
    .Call(`_sparseutils_sparseSandwichDiag`, L, M, Q, R, n, n0)
}

denseTraceProd <- function(A, B) {
    .Call(`_sparseutils_denseTraceProd`, A, B)
}

